FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY ml_pipeline.py .

RUN python ml_pipeline.py

ENV MODEL_PATH=models/new_model.pkl
ENV MODEL_TYPE=canary
ENV MODEL_VERSION=v1.0.0

EXPOSE 5000

CMD ["python", "app.py"]
